<?php

$_lang['dnepritnewsletter_queue_prepare'] = 'Сформировать очередь';
$_lang['dnepritnewsletter_queue_prepare_title'] = 'Подготовка рассылки';
$_lang['dnepritnewsletter_queue_send_now'] = 'Начать отправку сразу после формирования очереди';
$_lang['dnepritnewsletter_queue_schedule'] = 'Дата и время';
$_lang['dnepritnewsletter_queue_scheduled_at'] = 'Запланировано';
$_lang['dnepritnewsletter_queue_warning'] = 'В очередь попадут только активные подписчики. Для каждого будет сохранена персональная копия темы и письма. После этого кампанию нельзя будет редактировать.';
$_lang['dnepritnewsletter_queue_prepared'] = 'Очередь сформирована: [[+count]] получателей.';
$_lang['dnepritnewsletter_queue_log_prepared'] = 'Создано [[+count]] писем. Начало отправки: [[+date]].';
$_lang['dnepritnewsletter_queue_start'] = 'Запустить рассылку';
$_lang['dnepritnewsletter_queue_sending_title'] = 'Отправка рассылки';
$_lang['dnepritnewsletter_queue_sending_start'] = 'Подготовка первого пакета писем…';
$_lang['dnepritnewsletter_queue_sending_progress'] = 'Обработано';
$_lang['dnepritnewsletter_queue_sending_waiting'] = 'Достигнут лимит или ожидается следующая попытка. Отправка продолжится автоматически через минуту.';
$_lang['dnepritnewsletter_queue_sending_complete_title'] = 'Рассылка завершена';
$_lang['dnepritnewsletter_queue_sending_complete'] = 'Очередь обработана.';
$_lang['dnepritnewsletter_queue_sending_error'] = 'Не удалось выполнить пакет отправки.';
$_lang['dnepritnewsletter_queue_sender_already_running'] = 'Отправка уже выполняется в этой вкладке.';
$_lang['dnepritnewsletter_queue_err_select_campaign'] = 'Выберите рассылку в таблице.';
$_lang['dnepritnewsletter_queue_err_not_ready'] = 'Сначала сформируйте очередь для этой рассылки.';
$_lang['dnepritnewsletter_queue_err_no_recipients'] = 'Нет активных подписчиков для этой рассылки.';
$_lang['dnepritnewsletter_queue_err_already_prepared'] = 'Эта рассылка уже подготовлена к отправке.';
$_lang['dnepritnewsletter_queue_err_already_exists'] = 'Для этой рассылки уже существуют записи в очереди.';
$_lang['dnepritnewsletter_queue_err_schedule_invalid'] = 'Укажите корректную дату и время отправки.';
$_lang['dnepritnewsletter_queue_err_schedule_past'] = 'Запланированное время должно быть минимум на минуту позже текущего.';
$_lang['dnepritnewsletter_queue_err_save'] = 'Не удалось создать письмо для [[+email]].';
$_lang['dnepritnewsletter_queue_err_campaign_save'] = 'Не удалось обновить состояние рассылки.';
$_lang['dnepritnewsletter_queue_err_transaction'] = 'Не удалось выполнить транзакцию формирования очереди.';
